services:
  postgres:
    image: postgres:16
    container_name: aiproductdb
    environment:
      POSTGRES_USER: aiproductdb
      POSTGRES_PASSWORD: aiproductdb
      POSTGRES_DB: aiproductdb
    ports:
      - "5432:5432"
    volumes:
      - aiproductdb:/var/lib/postgresql/data

volumes:
  aiproduct:
